/*
(Initially) Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/cat-scene.glb

modified for this
*/

import * as THREE from "three";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { type ThreeElements, useGraph } from "@react-three/fiber";
import { useAnimations, useGLTF } from "@react-three/drei";
import { type GLTF, SkeletonUtils } from "three-stdlib";
import { CatController } from "../../common/CatController.ts";

type GLTFResult = GLTF & {
  nodes: {
    pelvis: THREE.Bone;
    leg_back_left_1: THREE.Bone;
    tail_1: THREE.Bone;
    leg_back_right_1: THREE.Bone;
    mesh_cat: THREE.SkinnedMesh;
    Plane: THREE.Mesh;
    Keyboard: THREE.Mesh;
  };
  materials: {
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: ThreeElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF("/cat-scene.glb");
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);

  const [catController] = useState(() => CatController.getController());

  const handleType = useCallback(() => {
    const shouldBeIdle = !catController.isTyping || catController.isDoneTyping;
    console.debug(
      "cat type:",
      shouldBeIdle,
      catController.isTyping,
      catController.isDoneTyping,
    );
    const typingAction = actions["Typing"];
    const keyboardAction = actions["KeyboardTyping"];
    if (!typingAction || !keyboardAction) return;

    if (shouldBeIdle) {
      // Transition to idle state
      typingAction.fadeOut(0.5);
      keyboardAction.fadeOut(0.5);

      actions["Sitting"]?.reset().fadeIn(0.5).play();
      actions["KeyboardIdle"]?.reset().fadeIn(0.5).play();
      return;
    }

    // Stop the idle animations
    actions["Sitting"]?.fadeOut(0.1);
    actions["KeyboardIdle"]?.fadeOut(0.1);

    if (!typingAction.isRunning()) {
      typingAction.reset().fadeIn(0.1).play();
    } else {
      typingAction.play();
    }

    if (!keyboardAction.isRunning()) {
      keyboardAction.reset().fadeIn(0.1).play();
    } else {
      keyboardAction.play();
    }
  }, [actions, catController]);

  useEffect(() => {
    actions["Sitting"]?.play();
    catController.attachTypeCallback(handleType);
  }, [actions, catController, handleType]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[0, 0, 1.211]}>
          <primitive object={nodes.pelvis} />
          <primitive object={nodes.leg_back_left_1} />
          <primitive object={nodes.tail_1} />
          <primitive object={nodes.leg_back_right_1} />
          <skinnedMesh
            name="mesh_cat"
            geometry={nodes.mesh_cat.geometry}
            material={materials["Material.003"]}
            skeleton={nodes.mesh_cat.skeleton}
          />
        </group>
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials["Material.002"]}
          position={[5, -0.13, 5]}
          scale={[8, 1, 8]}
        />
        <mesh
          name="Keyboard"
          geometry={nodes.Keyboard.geometry}
          material={materials["Material.001"]}
          position={[0.185, -0.118, 0.004]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/cat-scene.glb");
